# An Orderbook Timeline Displayed in Jupyter Notebook
- October 2025, Alan Lenarcic

Note to really run this notebook you need a working Python environment with ```pyrus_kaiko`` package installed and the ```gpuorderbook``` functionality compiled with ES builder.

See README for ```gpuorderbook``` installation.

We hope to be able to compile this Notebook to HTML using nbconvert

## Here we use anywidget to render javascript inside a jupyter notebook.  We use ```pyrus_kaiko`` package to simulate orderbook data.

# nbconvert will be required to export as htm

To try from command line
```jupyter nbconvert --to html --execute Demo_GPUOB.ipynb```

## Not quite sure on anywidget functionality

 The HTML version of this notebook definitely renders some aspects of the GPU notebook when opened separately in Chrome (outside of jupyter server).  That said the render is not entirely clean.

In [1]:
from pyrus_kaiko import pyrus_kaiko
## Note that pyo3 has changeable module inclusion adivce
## Here we use a "from pyrus_package import pyrus_package" interface which runs our "__init__.py" script

 pyrus_kaiko first try to from import
"asjoin_py" is part of "dir(pyrus_kaiko)"
------------------- pyrus_kaiko::__init__.py  running ---------- ---
-- dir(pyrus_kaiko) is [__all__,__doc__,__file__,__loader__,__name__,__package__,__spec__,asjoin_py,cumulate,kaiko_fob,kaiko_make_u_fob,limit_hit,pyrus_verify_prices,test_pa,unsorted_asjoin_py]
--- Thank you for running init.
-- dir(pk) is [__all__,__doc__,__file__,__loader__,__name__,__package__,__spec__,asjoin_py,cumulate,kaiko_fob,kaiko_make_u_fob,limit_hit,pyrus_verify_prices,test_pa,unsorted_asjoin_py]
-------------------------------------------------------------

In [2]:
import os; 
from pyrus_kaiko import pyrus_kaiko;
from pyrus_kaiko import ob;

nGen=20000; #nGen = 5000; 
nMidPoints = 4000;
import numpy as np; import pandas as pd;
import pyarrow as pa;
out_t, nr, v_d_fake, bprices, sprices, \
  write_sum_q, write_sum_pq, write_avp, write_worstpi, \
  write_nlevels, write_atq, \
  v_w, verbose, time_minmax, a_Fake_OB, MidTable = \
  ob.fake_for_algo(nGen = nGen,nMidPoints=nMidPoints,AddMidPrice=True, deltaSec=.01, v_bhit=False,fast_check="PARALLEL");

Fake_OB(Vb=1,nG=20000):  -- Begin
Fake_OB(Vb=1,nG=20000):  -- Fake_OB Generated mid_of_v, now makign add points
Fake_OB(Vb=1,nG=20000): : testing v_t1lc length 30000 for data against midpoints at 6000 points.
Fake_OB(Vb=1,nG=20000):  -- Trying to create minimum usage times using pyrus_verify_prices algorithms.
Fake_OB(Vb=1,nG=20000):  we calculated MiPrices, now we will join our v_t1o hits to MidPrice table to identify points.
Fake_OB(Vb=1,nG=20000):  after that we hit [1 1 1 ... 0 0 0]/30000 prices, next we perform a shrinking

In [3]:
# fake NBBO from the fake Midpoint
import copy
pd_dem = copy.copy(MidTable);
pd_dem = pd_dem[(pd_dem.time <= time_minmax[1]) & (pd_dem.time.shift(-1,fill_value=time_minmax[1])  >= time_minmax[0])].reset_index(inplace=False, drop=True)
rtt = pd_dem['time'].copy().to_numpy(); rtt[rtt < time_minmax[0]] = time_minmax[0];
pd_dem['time'] = rtt;
pd_dem['best_bid'] = pd_dem['nbm'] - .01;
pd_dem['best_ask'] = pd_dem['nbm'] + .01;
pd_dem['b_sum_q_1'] = 100;
pd_dem['s_sum_q_1'] = 100;

In [4]:
a_Fake_OB['t0'].astype('datetime64[ns]').min()

Timestamp('2024-10-03 10:30:31.999999')

In [5]:
"""
# Use if you want to calculate bestbid/ask from an algorithm
out_t['time'] = out_t['time'].astype('datetime64[ns]')
kalgoint_basic = np.array([0], dtype=np.uint8)[0];
v_d = np.asarray([1], dtype=np.int64); verbose_book = 0;
import time; 
time_00 = time.time();
out_PMB = pyrus_marketbook.pyrus_bbo_algo(out_t, nr, v_d, 
  bprices, sprices, kalgoint_basic,
  1, 0, 0, 0, 0, 0,
  v_w, verbose_book, time_minmax.astype(np.int64) );
time_01 = time.time();
print("pd_dem calculated from " + str(len(out_t)) + " recs in " + str(time_01-time_00) + " sec.");
pd_dem = pa.Table.from_batches([out_PMB]).to_pandas();
pd_dem = pd_dem[(pd_dem['best_bid'] > 0) & (pd_dem['best_ask'] > 0)].reset_index(inplace=False, drop=True)
"""

'\n# Use if you want to calculate bestbid/ask from an algorithm\nout_t[\'time\'] = out_t[\'time\'].astype(\'datetime64[ns]\')\nkalgoint_basic = np.array([0], dtype=np.uint8)[0];\nv_d = np.asarray([1], dtype=np.int64); verbose_book = 0;\nimport time; \ntime_00 = time.time();\nout_PMB = pyrus_marketbook.pyrus_bbo_algo(out_t, nr, v_d, \n  bprices, sprices, kalgoint_basic,\n  1, 0, 0, 0, 0, 0,\n  v_w, verbose_book, time_minmax.astype(np.int64) );\ntime_01 = time.time();\nprint("pd_dem calculated from " + str(len(out_t)) + " recs in " + str(time_01-time_00) + " sec.");\npd_dem = pa.Table.from_batches([out_PMB]).to_pandas();\npd_dem = pd_dem[(pd_dem[\'best_bid\'] > 0) & (pd_dem[\'best_ask\'] > 0)].reset_index(inplace=False, drop=True)\n'

In [6]:
nTrades = 200; trade_i = np.asarray(np.unique(np.random.choice(np.arange(len(pd_dem)), nTrades, replace=False)))
ts = np.random.choice(np.asarray([0,1]),nTrades)
trades =  pd_dem.iloc[trade_i].reset_index(inplace=False, drop=True);
tprice = trades['best_bid'].to_numpy();
tprice[ts == 0] == trades['best_ask'].to_numpy()[ts == 0]
tqty = trades['b_sum_q_1'];  tqty[ts==0] == trades['s_sum_q_1'][ts==0];
trades = pd.DataFrame({'time':trades['time'],'price':tprice,'qty': (-2*ts + 1) * tqty})
trades['time'] = (trades['time']-pd_dem['time'][0]).astype(np.int64)/1000000000.0

trades

      time     price  qty
0     0.02   9995.99  100
1     0.08   9996.99 -100
2     0.19  10008.99 -100
3     0.34   9974.99 -100
4     0.43   9971.99 -100
..     ...       ...  ...
195  38.92   9814.99 -100
196  39.16   9808.99  100
197  39.40   9828.99  100
198  39.47   9838.99 -100
199  39.67   9836.99  100

[200 rows x 3 columns]

In [7]:
dt = str(time_minmax[0])[0:10]; st_time =  str(time_minmax[0])[11:26]; unit = 0;
time0 = time_minmax[0];
nbbo = pd_dem[['time','best_bid','best_ask']].reset_index(inplace=False, drop=True); nbbo.columns = ['time','nbb','nbo']; nbbo['time'] = ((nbbo['time'] - time0).astype(np.int64)) / 1000000000.0
tmin = np.min(nbbo['time']); tmax = np.max(nbbo['time']);
inner_pmin = np.min(nbbo['nbb']);  inner_pmax = np.max(nbbo['nbo']);
pmin = inner_pmin - 1 * (inner_pmax - inner_pmin);  pmax = inner_pmax + 1 * (inner_pmax - inner_pmin);
height = 400; width = 800;
lwd_h = .01; lwd_w = (400/800) * lwd_h;
max_qty = np.max(out_t['cm_qty']); pow_qty = .25;
trade_mul_fac=.1; msg_mul_fac = .1;
buys = a_Fake_OB[a_Fake_OB['bs'] == b'b'][['price','qty','t0','t1']].reset_index(inplace=False, drop=True); buys['t0'] = (buys['t0'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;  buys['t1'] = (buys['t1'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;
buys.columns = ['price', 'qty', 'open','close']
buys

sells = a_Fake_OB[a_Fake_OB['bs'] == b's'][['price','qty','t0','t1']].reset_index(inplace=False, drop=True); sells['t0'] = (sells['t0'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;  sells['t1'] = (sells['t1'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;
sells.columns = ['price', 'qty', 'open','close']
sells
data_type = 'generated_data';

In [8]:
out_t
mxtime = np.max(out_t['time']);
buys = out_t[out_t['side'] == b'b'][['price','cm_qty','time']].reset_index(inplace=False,drop=True);
close = buys['time'].shift(-1,fill_value=mxtime);
close[buys['price'] != buys['price'].shift(-1,fill_value=-1)] = mxtime; buys['close'] = close;  buys.columns = ['price','qty','open','close'];  
buys['open'] = (buys['open'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;  
buys['close'] = (buys['close'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;
buys = buys[buys.qty > 0].reset_index(inplace=False, drop=True)

sells = out_t[out_t['side'] == b's'][['price','cm_qty','time']].reset_index(inplace=False,drop=True);
close = sells['time'].shift(-1,fill_value=mxtime);
close[sells['price'] != sells['price'].shift(-1,fill_value=-1)] = mxtime; sells['close'] = close;  sells.columns = ['price','qty','open','close'];  
sells['open'] = (sells['open'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;  
sells['close'] = (sells['close'].astype('datetime64[ns]') - time0).astype(np.int64) / 1000000000.0;
sells = sells[sells.qty > 0].reset_index(inplace=False, drop=True);
sells

         price     qty       open      close
0       9807.0   592.0  37.936786  37.939379
1       9808.0    81.0  38.050117  38.059586
2       9809.0   454.0  37.893638  37.923417
3       9809.0   760.0  37.965748  38.025161
4       9811.0    59.0  37.969340  37.988184
...        ...     ...        ...        ...
17057  10214.0   618.0  -0.000001   1.504691
17058  10218.0  1017.0  -0.000001   0.539030
17059  10218.0    70.0   0.539030   1.028811
17060  10236.0   447.0  -0.000001   1.532442
17061  10238.0   725.0  -0.000001   5.000929

[17062 rows x 4 columns]

In [9]:
test_data = { "dt": dt, 'st_time':st_time, 'unit':unit, 'tmin':tmin, 'tmax':tmax, 'pmin':pmin, 'pmax':pmax,'height':height, 'width':width,
                'lwd_h':lwd_h, 'lwd_w':lwd_w, 'max_qty':max_qty, 'pow_qty':pow_qty,'trade_mul_fac':trade_mul_fac, 'msg_mul_fac':msg_mul_fac,
                'nbbo':nbbo.to_dict(orient='list'),'buys':buys.to_dict(orient='list'),'sells':sells.to_dict(orient='list'),'trades':trades.to_dict(orient='list'),'data_type':'generated_data'};
import json;
aD = json.dumps(test_data)

In [10]:
import pathlib
import anywidget
import traitlets
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% ! important; }</style>"))


from IPython.display import HTML, display
#html_code = "<h1>Hello, world!</h1><p>This is a paragraph.</p>"
#install_div_space = \
#"""<div id="gl_div" name="gl_div"> <div>"""
#display(HTML(install_div_space))

class obwidget(anywidget.AnyWidget):
    _esm = "./outwidget/static/widget_index.js"
    _css = "./outwidget/static/widget_index.css"
    data = traitlets.Dict(test_data).tag(sync=True)
    value = traitlets.Int(0).tag(sync=True)

obwidget()

In [11]:

UNCOMMENT_FOR_TEST_WIDGET = """
import pathlib
import anywidget
import traitlets
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% ! important; }</style>"))


from IPython.display import HTML, display
html_code = "<h1>Hello, world!</h1><p>This is a paragraph.</p>"
install_div_space = "<div id=\"gl_div\" name=\"gl_div\"> <div>"
display(HTML(install_div_space))

class obwidget(anywidget.AnyWidget):
    _esm = "./outwidget/static/widget_index.js"
    _css = "./outwidget/static/widget_index.css"
    value = traitlets.Int(0).tag(sync=True)

obwidget()
"""

In [12]:
# To execute and save as HTML
# jupyter nbconvert --execute --to HTML Demo_GPUOB.ipynb